//Array that holds the player initial resources
var playerInitialResource = [
	{
		"name":"Population",
		"type":0,
		"currentAmount":30,
		"totalCapacity":30,
		"amountPerLevel":0
	},
	{
		"name":"Food",
		"type":1,
		"currentAmount":1000,
		"totalCapacity":1000,
		"amountPerLevel":20
	},
	{
		"name":"Wood",
		"type":2,
		"currentAmount":1000,
		"totalCapacity":1000,
		"amountPerLevel":0
	},
	{
		"name":"Rocks",
		"type":3,
		"currentAmount":0,
		"totalCapacity":1000,
		"amountPerLevel":0
	},
	{
		"name":"Copper",
		"type":4,
		"currentAmount":0,
		"totalCapacity":1000,
		"amountPerLevel":0
	},
	{
		"name":"Iron",
		"type":5,
		"currentAmount":0,
		"totalCapacity":1000,
		"amountPerLevel":0
	},
	{
		"name":"Coal",
		"type":6,
		"currentAmount":0,
		"totalCapacity":1000,
		"amountPerLevel":0
	},
	{
		"name":"Gold",
		"type":7,
		"currentAmount":0,
		"totalCapacity":1000,
		"amountPerLevel":0
	},
	{
		"name":"Oil",
		"type":8,
		"currentAmount":0,
		"totalCapacity":1000,
		"amountPerLevel":0
	}
	/* skeleton in case it is needed in the future
	{
		"name":"",
		"type":"",
		"currentAmount":"",
		"totalCapacity":"",
		"amountPerLevel":""
	},*/
];